language: node_js
node_js:
  - "8.1"
jobs:
  include:
    - stage: Backend
      script:
        - cd backend
        - npm install
        - npm run lint
        - npm run test
        - cd ..
    - stage: Frontend
      script:
        - npm run lint
        - npm run build
        - npm test
cache:
  directories:
    - node_modules
    - backend/node_modules
