#######################
# Frontend Service v2 #
#######################
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: frontend-service-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-service
        version: v2
    spec:
      containers:
        - name: frontend-service
          image: us.gcr.io/dev-619/front:v1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
